### ISSUE TITLE
Test1 -Login 

### ISSUE THREAD

**Issue by pritom02bh** [hillubhai/DesignLab#1]
The System is failed to show the Dash page after a successful Login.
Steps to re-create
1.Enter email=abc@gmail.com
2.Password=xyz123
3.Login successful
4.The system shows the Dash page.

**Comment by Parvani167** [comment]
The Login and Register bugs have been fixed .

**Comment by pritom02bh** [comment]
The issue is fixed by Developer Team. --QA Team
After a successful login, the system shows the donor/volunteer home page.
